name: Update AUTHORS
on:
  push:
    branches:
      - main
jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update time
        run: |
          spark_version="2.4.$((RANDOM%10))"
          bigdl_version="2.2.$((RANDOM%10))"
          echo $spark_version-$bigdl_version
          sed "s:[0-9]*\.[0-9]*\.[0-9]*[/-][0-9]*\.[0-9]*\.[0-9]*:$spark_version/$bigdl_version:g" README.md
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.AUTOMERGE }}
          commit-message: update authors
          title: Update AUTHORS
          body: Credit new contributors by updating AUTHORS
          branch: update-authors2
      - run: echo ${{ steps.cpr.outputs.pull-request-number }}
      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.AUTOMERGE }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
